À medida que os veículos elétricos (VEs) se tornam mais populares, há uma necessidade crescente de acesso a estações de recarga, também conhecidas como pontos de carregamento. Para isso, muitos prédios residenciais modernos começaram a adaptar suas garagens para incluir estações de recarga compartilhadas. Uma estação de recarga é considerada compartilhada se for acessível por qualquer pessoa do prédio.

<img src="charging_station.jpg" alt="Carregamento de VE" width="500" height="auto">

Mas, com o aumento da demanda, cresce também a competição por esses pontos — nada é mais frustrante do que chegar em casa e não encontrar nenhuma estação de recarga disponível! Neste projeto, você usará um conjunto de dados para ajudar administradores de prédios residenciais a entender melhor os hábitos de recarga de seus moradores.

Os dados foram carregados em um banco de dados PostgreSQL com uma tabela chamada `charging_sessions` com as seguintes colunas:

## charging_sessions

| Coluna | Definição | Tipo de dado |
|-|-|-|
|`garage_id`| Identificador da garagem/prédio |`VARCHAR`|
|`user_id` | Identificador do usuário individual |`VARCHAR`|
|`user_type`| Indica se a estação é `Shared` (Compartilhada) ou `Private` (Privada) | `VARCHAR` |
|`start_plugin`| Data e hora de início da sessão |`DATETIME`|
|`start_plugin_hour`| Hora (em formato 24h) em que a sessão começou | `NUMERIC`|
|`end_plugout`| Data e hora de término da sessão | `DATETIME` |
|`end_plugout_hour`| Hora (em formato 24h) em que a sessão terminou | `NUMERIC`|
|`duration_hours`| Duração da sessão, em horas |`NUMERIC`|
|`el_kwh`| Quantidade de eletricidade utilizada (em quilowatt-hora) |`NUMERIC`|
|`month_plugin`| Mês em que a sessão começou |`VARCHAR`|
|`weekdays_plugin`| Dia da semana em que a sessão começou |`VARCHAR`|

Vamos começar!

#### Fontes
- **Dados**: [CC BY 4.0](https://creativecommons.org/licenses/by/4.0), via [Kaggle](https://www.kaggle.com/datasets/anshtanwar/residential-ev-chargingfrom-apartment-buildings)
- **Imagem**: Julian Herzog, [CC BY 4.0](https://creativecommons.org/licenses/by/4.0), via Wikimedia Commons

In [4]:
-- unique_users_per_garage
-- Modify the code below
SELECT  garage_id,  
	COUNT(DISTINCT user_id) AS num_unique_users
FROM charging_sessions
WHERE user_type = 'Shared'
GROUP BY garage_id
ORDER BY num_unique_users DESC

  garage_id  num_unique_users
0       Bl2                18
1      AsO2                17
2       UT9                16
3      AdO3                 3
4       MS1                 2
5       SR2                 2
6      AdA1                 1
7       Ris                 1

In [5]:
SELECT weekdays_plugin, start_plugin_hour, COUNT(*) AS num_charging_sessions
FROM charging_sessions
WHERE USER_TYPE = 'Shared'
GROUP BY weekdays_plugin, start_plugin_hour
ORDER BY num_charging_sessions DESC
LIMIT 10

  weekdays_plugin  start_plugin_hour  num_charging_sessions
0          Sunday                 17                     30
1          Friday                 15                     28
2        Thursday                 16                     26
3        Thursday                 19                     26
4          Sunday                 18                     25
5          Sunday                 15                     25
6       Wednesday                 19                     25
7          Monday                 15                     24
8          Friday                 16                     24
9          Sunday                 14                     23

In [6]:
-- long_duration_shared_users
SELECT user_id, AVG(duration_hours) AS avg_charging_duration
FROM charging_sessions
WHERE USER_TYPE = 'Shared' 
GROUP BY user_id
HAVING AVG(duration_hours) > 10
ORDER BY avg_charging_duration DESC
LIMIT 6

    user_id  avg_charging_duration
0   Share-9              16.845833
1  Share-17              12.894556
2  Share-25              12.214475
3  Share-18              12.088807
4   Share-8              11.550431
5    AdO3-1              10.369387